[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc.exe"
ar = "x86_64-w64-mingw32-gcc-ar.exe"
rustflags = ["-C", "link-args=-static-libgcc -static-libstdc++ -static-libwinpthread"]

[build]
jobs = 16

[env]
CFLAGS = "-Wa,-mbig-obj"
CXXFLAGS = "-Wa,-mbig-obj"
CC_x86_64_pc_windows_gnu = "x86_64-w64-mingw32-gcc.exe"
CXX_x86_64_pc_windows_gnu = "x86_64-w64-mingw32-g++.exe"
